#!/bin/sh

__ARG=$1

__START_LOCAL_DOCKER="start:docker"
__STOP_LOCAL_DOCKER="stop:docker"
__START_REACT="start:react"
__UPDATE_CORE_LIB="update:core"

__CURRENT_UID=$(id -u):$(id -g)
export __CURRENT_UID

if [[ "$__ARG" == "$__START_LOCAL_DOCKER" ]]; then
    shift
    if [[ "$(docker images -q hiramlabs/openresty 2> /dev/null)" == "" ]]; then
        docker build -t hiramlabs/openresty "$@" .
    fi
    docker run \
        "$@" \
        -d \
        -p 9001:80 \
        --name openresty \
        --restart=unless-stopped \
        hiramlabs/openresty
fi

if [[ "$__ARG" == "$__STOP_LOCAL_DOCKER" ]]; then
    shift
    docker stop "$@" openresty
fi

if [[ "$__ARG" == "$__START_REACT" ]]; then
    shift
    npm --prefix web run start
fi

if [[ "$__ARG" == "$__UPDATE_CORE_LIB" ]]; then
    shift
    npm --prefix core run build \
    && mkdir -p ./web/src/lib/armulator_core \
    && cp -a ./core/dist/*modern* ./web/src/lib/armulator_core
fi
