#!/bin/sh

__ARG=$1

__START_DOCKER="start"
__STOP_DOCKER="stop"

__CURRENT_UID=$(id -u):$(id -g)
export __CURRENT_UID

if [[ "$__ARG" == "$__START_DOCKER" ]]; then
    shift
    if [[ "$(docker images -q hiramlabs/openresty 2> /dev/null)" == "" ]]; then
        docker build -t hiramlabs/openresty "$@" .
    fi
    docker run \
        "$@" \
        -d \
        -p 9001:80 \
        -p 9002:443 \
        --name openresty \
        --restart=unless-stopped \
        hiramlabs/openresty
fi

if [[ "$__ARG" == "$__STOP_DOCKER" ]]; then
    shift
    docker stop "$@" openresty
fi
